<template>
  <div class="privacy-policy-root">
    <h2 class="title">Privacy Policy</h2>
    <div class="publish-date">Last updated: {{ lastUpdated }}</div>
    <div class="foreword">
      In plain terms, I do not collect <strong>any</strong> information from you
      when you visit this site.
      <p>
        In full (informal) terms: This site is hosted on Github Pages, which
        does not allow me to save any data on the server. It does not connect to
        any other server, except to fetch resources such as images - No data is
        sent from this site to any location I have control over.
      </p>
      <p>
        Pages also does not provide me with any statistics regarding who is
        viewing this site, or how many times it is viewed. I do not inject
        Google Analytics or another script which would collect that information
        from your browser either - In short, I know nothing more about you after
        you've seen this site compared to before you came here, neither as an
        individual or aggregated into a pool of however many people have seen
        this (I don't even know that much!).
      </p>
      <p>
        A more detailed, more formal description of this arrangement follows
        below:
      </p>
    </div>
    <hr />
    <p>
      This Privacy Policy describes My policies and procedures on the
      collection, use, and disclosure of Your information when You use the
      Service, and tells You about Your privacy rights and how the law protects
      You.
    </p>
    <p>
      I do not use Your Personal data for any reason, including to provide or
      improve the Service. By using the Service, You agree that you have been
      informed that I do not use any such information. You are not required to
      agree to share any information or permit Me to collect any information in
      order to use the Service.
    </p>
    <h3>Interpretation and Definitions</h3>
    <h4>Interpretation</h4>
    <p>
      Some words for which the initial letter is capitalized have meanings
      defined under the following conditions. The following definitions shall
      have the same meaning regardless of whether they appear in singular or in
      plural.
    </p>
    <h4>Definitions</h4>
    <p>For the purposes of this Privacy Policy:</p>
    <ol>
      <li>
        <strong>Account</strong> means a unique account created for You to
        access the Service, in whole or in part.
      </li>
      <li>
        <strong>Author</strong> (referred to as either "the Author", "I", "Me"
        or "My" in this Agreement) refers to Ryan Hodin.
      </li>
      <li>
        <strong>Cookies</strong> are small files that are placed on Your Device
        by a website, containing some details of Your history in interacting
        with that website among its many uses.
      </li>
      <li>
        <strong>Country</strong> refers to the United States, or to the State of
        Illinois, as appropriate.
      </li>
      <li>
        <strong>Device</strong> means any device that can access the Service
        such as a computer, a cellphone, or a digital tablet.
      </li>
      <li>
        <strong>Personal Data</strong> is any information that relates to an
        indentified or identifiable individual.
      </li>
      <li>
        <strong>Service</strong> (referred to as either the "Service" or the
        "Website" in this Agreement) refers to the personal website of the
        Author, where this Privacy Policy is found (hosted at
        <router-link to="/">https://za419.github.io/</router-link>)
      </li>
      <li>
        <strong>Usage Data</strong> refers to data collected automatically,
        either generated by the use of the Service or from the Service
        infrastructure itself (for example, the duration of a page visit).
      </li>
      <li>
        <strong>You</strong> means the individual accessing or using the
        Service, or the company, or other legal entity on behalf of which such
        individual is accessing or using the Service, as applicable.
      </li>
    </ol>
    <h3>Collecting and Using Your Personal Data</h3>
    <h4>Types of Data Collected</h4>
    <h5>Personal Data</h5>
    <p>
      While using My Website, I will not ask You to provide Me with any
      personally identifiable information that can be used to contact or
      identify You. I will only receive such information about You if You choose
      to share it with me, for example by use of the contact information
      available at the bottom of each page of the Website.
    </p>
    <h5>Usage Data</h5>
    <p>No usage data is collected automatically when using the Service.</p>
    <p>
      I do not receive any such information, such as Your Device's Internet
      Protocol address (otherwise known as an IP address), browser type, browser
      version, the pages of the Website that You visit, the time and date of
      Your visit, the time spent viewing those pages, unique device identifiers,
      or other diagnostic data.
    </p>
    <p>
      Your browser does not send information to Me or to another location
      controlled by Me when you access the Service, by or through any Device.
    </p>
    <h5>Tracking Technologies and Cookies</h5>
    <p>
      I do not use Cookies or similar tracking technologies to track the
      activity on My Website or to store any information. Examples of such
      tracking technologies includes beacons, tags, or scripts which collect and
      track information or to improve and analyze the Service.
    </p>
    <h4>Use of Your Personal Data</h4>
    <p>The Author does not use Your Personal Data for any purpose.</p>
    <h4>Retention of Your Personal Data</h4>
    <p>
      The Author will not retain Your Personal Data or Your Usage Data for any
      length of time. I do not collect any Personal Data or Usage Data which I
      could use to enforce any legal agreement, or for internal analysis
      purposes.
    </p>
    <h4>Transfer of Your Personal Data</h4>
    <p>
      Your information, including Your Personal Data, is not processed by Me or
      by anyone representing Me. I will not transfer Your data to any computer,
      or maintain it on any computer, located in Your local jurisdiction, or in
      another one where data protection laws may differ from those local to You.
    </p>
    <h4>Disclosure of Your Personal Data</h4>
    <p>
      I will not transfer or disclose Your Personal Data to any entity unless it
      becomes required of me to collect and disclose it to public authorities
      (such as a court or government agency) in the future when I am made aware
      of a legal obligation for me to do so.
    </p>
    <h4>Security of Your Personal Data</h4>
    <p>
      The security of Your Personal Data is important to Me. I do not store any
      such data, and no security violation of My computers will result in a leak
      of previously collected data. If I am obligated to collect information
      from You in the future, I will use the best means available to me to
      protect Your Personal Data and its security in the future. However, no
      method of transmission or storage is 100% secure.
    </p>
    <p>
      Additionally, please note that should My Website be compromised before it
      reaches Your Device, it may be used as a &quot;Trojan Horse&quot; to take
      information from You. Although I will not collect any information from
      You, I suggest that You should not trust this Website with any data that
      you consider confidential, as a matter of personal information security.
    </p>
    <h3>Children's Privacy</h3>
    <p>
      My Website does not address aanyone under the age of 13. I do not
      knowingly collect personally identifiable information from anyone above or
      below the age of 13.
    </p>
    <h3>Links to Other Websites</h3>
    <p>
      My Service may contain links to other websites that are not operated by
      Me. If You click on a third party link, You will be directed to that third
      party's site. I strongly advice You to review the Privacy Policy of every
      site You visit.
    </p>
    <p>
      I have no control over, and assume no responsibility for, the content,
      privacy policies, or practices of any third party sites or services.
    </p>
    <h3>Changes to this Privacy Policy</h3>
    <p>
      I may update My Privacy Policy from time to time. I will post the new
      Privacy Policy on this page at the same time it becomes active or
      applicable. This will include an update to the &quot;Last updated&quot;
      date at the top of this Privacy Policy.
    </p>
    <p>
      Viewing this Website does not provide me with any way to contact you
      personally, so I cannot let You know via email or another method when it
      is updated. If You would like to be informed of such updates, You may
      contact Me to request such updates and provide Me with Your preferred
      method by which You would like Me to provide You with notice of such
      updates.
    </p>
    <p>
      You are advised to review this Privacy Policy periodically for any
      changes. Changes to this Privacy Policy are effective when they are posted
      on this page.
    </p>
    <h3>Contact Me</h3>
    <p>
      If you have any questions about this Privacy Policy, You can contact Me by
      any of the methods at the bottom of this page.
    </p>
  </div>
</template>

<script lang="ts">
import Vue from "vue";

export default Vue.extend({
  data(): Record<string, string> {
    return {
      // Last updated datestamp: Update this whenever the policy changes
      // As if that's going to be often...
      lastUpdated: new Date(
        "Fri Sep 17 2021 19:36:42 GMT-0500"
      ).toLocaleDateString(undefined, {
        year: "numeric",
        month: "long",
        day: "2-digit",
      }),
      pageTitle: "Privacy Policy - Ryan Hodin",
      pageDescription:
        "An in-depth description of all the personal information I don't collect.",
    };
  },
});
</script>

<style lang="scss">
.privacy-policy-root {
  width: 75%;
  max-width: 1250px;
  margin: auto;

  p {
    margin-top: 1em;
  }

  h2.title {
    margin-top: 1em;
    margin-bottom: 0.35em;
  }

  div.publish-date {
    margin-bottom: 2em;
    font-size: 0.95em;
    font-weight: 300;
    color: rgba(0, 0, 0, 0.8);
  }

  div.foreword {
    margin-bottom: 1em;
  }
}

@media screen and (orientation: portrait) {
  .privacy-policy-root {
    width: 85%;
  }
}

@media screen and (min-width: 1250px) {
  .privacy-policy-root {
    font-size: 1.2em;
  }
}
</style>
